### ISSUE TITLE
Can't execute meshcentral assistant in system tray ,always connected

### ISSUE THREAD

**Issue by jefflin0902** [Ylianst/MeshCentralAssistant#19]
I download meshcentral assistant  the "system tray ,always connected" then execute it,
But it not work, and create a txt file .....

debug.txt
--------------------------------
UnhandledExceptionEventSink: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at MeshAssistant.MeshCentralAgent.checkMshStr(String mshstr)
   at MeshAssistant.MainForm..ctor(String[] args)
   at MeshAssistant.Program.Main(String[] args)
-----------------------------------

**Comment by Ylianst** [comment]
Seems like your .MSH file has the same key multiple times. I put in a fix for this, only the first key value will be used if the same key is present multiple times.

**Comment by jefflin0902** [comment]
It is fixed, Thanks
