### ISSUE TITLE
 Invalid URI exception

### ISSUE THREAD

**Issue by alialpsln** [Ylianst/MeshCentralAssistant#4]
Windows7  64bit Home Edition client application crashes. Meshagent already installed and connected.
Exception detail is as follows:

UnhandledExceptionEventSink: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at MeshAssistant.MeshAgent.ReadPipe(IAsyncResult r)
   at System.IO.Pipes.PipeStream.AsyncPSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by Ylianst** [comment]
Fixed this in new version of MeshCentral Assistant that will be in MeshCentral v0.7.4.

**Comment by alialpsln** [comment]
Thank you @Ylianst
